#!/bin/bash

# converts a whole directory using openoffice/libreoffice and html tidy
# Originally from http://www.techrepublic.com/blog/linux-and-open-source/how-to-convert-doc-and-odf-files-to-clean-and-lean-html/

CONFIG=/home/steven/.config/htmltidy.conf

# NOTE - this config removes all font and center tags!

#clean: yes
#enclose-text: yes
#drop-empty-paras: yes
#drop-font-tags: yes
#drop-proprietary-attributes: yes
#output-html: yes
#input-encoding: utf8
#output-encoding: utf8
#join-classes: yes
#join-styles: yes
#show-body-only: yes
#force-output: yes
#new-inline-tags: sup, u	
#wrap: 0
#merge-divs: yes
#merge-spans: yes
#preserve-entities: yes
#output-xhtml: yes


function check_args {
	if [ $# -lt 2 ]; then
		to=$PWD
	else
		to=$2
	fi
	if [ $# -lt 1 ]; then
		from=$PWD
	else
		from=$1	
	fi
	#add error check here for output dir
	echo "Using $to as output directory and $from as input directory."
}

function process_filetypes {
	#changed this in order to catch spaces properly
	for F in *.$filetype
	do
  		# replacing all spaces with underscores, marking that we have changed the filename
  		new="${F// /_}"
 	 	if [ "$new" != "$F" ];then
			if [ -e "$new" ];then
				echo not renaming \""$f"\" because \""$new"\" already exists
			else
				cp "$F" "$new"
				F="$new"
				changed=1
    			fi
		fi
		if [ -f "$F" ]; then
			file=$(basename "$F")
			BASE=${file%.*}
			soffice --headless --convert-to htm:HTML --outdir $to $F

			# Fixes underscore tag to italics.  We hateses underscore tags.
			cat $BASE.htm | sed -s 's|<U[^>]*>|<i>|g' | sed -s 's|</U[^>]*>|</i>|g' > $BASE.ht1
			# Fixes smart quotes part one  - changing existing to HTML
			cat $BASE.ht1 | sed 's|”|\&rdquo;|g' | sed 's|“|\&ldquo;|g' | sed 's|’|\&rsquo;|g' > $BASE.ht2
			# note the sed line at the end that removes the class descriptors and language descriptors
			tidy -q -config $CONFIG -f $to/$BASE.err -i $to/$BASE.ht2 | sed 's/ class="[^>]*"//g' | sed 's/ lang="[^>]*">/>/g' > $to/$BASE.ht3
			
			# fix smart quotes part two - converting straight quotes to smart quotes.  This will get a LOT of them.
			cat $BASE.ht3 | sed 's|\&quot; |\&rdquo; |g' | sed 's| \&quot;| \&ldquo;|g' | sed 's|\&quot;<|\&rdquo;<|g' | sed 's|>\&quot;|>\&ldquo;|g' | sed "s|'|\&rsquo;|g" >> $BASE.ht4
			
			# Note - This uses the base.html file included in the repository to format it into full html pages.
			head -n 13 /home/steven/Vault/base.html > $BASE.html
			echo " " >> $BASE.html 
			cat $BASE.ht4 >> $BASE.html 
			echo " </body>" >> $BASE.html
			echo "</html>" >> $BASE.html
			
		fi
		if [ "$changed" == "1" ]; then
			changed=0;
			rm -f $new
		fi
		# uncomment these to get the error log and other temp steps back
		rm -f $BASE.err
		rm -f $BASE.htm
		rm -f $BASE.ht4		
		rm -f $BASE.ht3
		rm -f $BASE.ht2
		rm -f $BASE.ht1
	done
}

# run the stuff for the different filetypes

check_args
filetype=odt
process_filetypes
filetype=doc
process_filetypes
filetype=docx
process_filetypes

